# fly.toml app configuration file generated for portfolio-elias-gill on 2025-01-19T19:57:09-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-elias-gill'
primary_region = 'eze'

[build]

[env]
  PORT = '8000'
  MAIN_PATH = '/app'
  BLOG_PATH = '/app/blog'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
