# fly.toml app configuration file generated for portfolio-elias-gill on 2025-01-19T19:25:36-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-elias-gill'
primary_region = 'eze'

[build]
  [build.args]
    GO_VERSION = '1.22.0'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
